"""Build the ASL alphabet reference sheet the translator's Reference button opens.

Primary path renders one sample per letter fresh through `preprocessing.render_skeleton`
-- the same function the model and the live translator use -- so the reference always
shows exactly what a correct sign looks like to the network, not a stock photo of one.
Needs `landmarks.npz` (see `prepare_dataset.py`), so it only runs on a machine that has
the training data.

Fallback path works with nothing but what's already in the repo: it slices the 26 tiles
out of `docs/render-check.png` (already checked in, generated by `check_render.py`) and
enlarges them. Lower resolution -- those tiles were rendered at 96px -- but it means the
Reference button has something to show even on a machine that never ran the pipeline.

    python build_reference.py                    # landmarks.npz if present, else fallback
    python build_reference.py --from-sheet        # force the fallback path
"""

import argparse
import os

import cv2
import numpy as np

import preprocessing as pp

TILE = 220
COLUMNS = 7
TITLE_H = 50


def from_landmarks(landmarks_path, tile):
    data = np.load(landmarks_path, allow_pickle=False)
    class_names = [str(c) for c in data["class_names"]]
    points = data["points"].astype(np.float32)
    labels = data["labels"].astype(int)

    images = []
    for i in range(len(class_names)):
        matches = np.where(labels == i)[0]
        if len(matches) == 0:
            images.append(np.zeros((tile, tile, 3), dtype=np.uint8))
            continue
        # The middle of the group rather than the first sample, so a run of near-duplicate
        # frames at the start of one class doesn't decide what "the" reference pose is.
        chosen = matches[len(matches) // 2]
        rendered = pp.render_skeleton(points[chosen], size=tile)
        images.append(cv2.cvtColor(rendered, cv2.COLOR_RGB2BGR))
    return class_names, images


def from_existing_sheet(sheet_path, tile):
    """Slice tiles out of check_render.py's default output and enlarge them.

    Hardcodes that script's default geometry (tile=96, columns=13, label_height=16)
    rather than reading it back out of the image, since nothing about a PNG says how it
    was tiled. If check_render.py's defaults ever change, regenerate render-check.png
    first and this will silently slice the wrong regions -- there is no way to detect
    that from the file alone, so this is a real fragility, not a hypothetical one.
    """
    sheet = cv2.imread(sheet_path, cv2.IMREAD_COLOR)
    if sheet is None:
        raise SystemExit(f"Error: could not read '{sheet_path}'.")

    src_tile, src_cols, label_h = 96, 13, 16
    cell = src_tile + label_h
    class_names = [chr(c) for c in range(ord("a"), ord("z") + 1)]

    expected_h, expected_w = 2 * cell, src_cols * src_tile
    if sheet.shape[:2] != (expected_h, expected_w):
        raise SystemExit(
            f"Error: '{sheet_path}' is {sheet.shape[1]}x{sheet.shape[0]}, expected "
            f"{expected_w}x{expected_h}. It was probably regenerated with different "
            "--tile/--columns; update the constants above to match, or run with "
            "--landmarks once landmarks.npz is available."
        )

    images = []
    for i in range(len(class_names)):
        r, c = divmod(i, src_cols)
        y, x = r * cell, c * src_tile
        crop = sheet[y:y + src_tile, x:x + src_tile]
        images.append(cv2.resize(crop, (tile, tile), interpolation=cv2.INTER_NEAREST))
    return class_names, images


def compose(class_names, images, tile, columns):
    label_h = 34
    cell = tile + label_h
    rows = (len(images) + columns - 1) // columns
    width, height = columns * tile, TITLE_H + rows * cell

    sheet = np.zeros((height, width, 3), dtype=np.uint8)
    cv2.putText(sheet, "ASL Alphabet Reference", (14, 34),
                cv2.FONT_HERSHEY_SIMPLEX, 0.85, (255, 255, 255), 2, cv2.LINE_AA)

    for i, (image, name) in enumerate(zip(images, class_names)):
        r, c = divmod(i, columns)
        y, x = TITLE_H + r * cell, c * tile
        sheet[y:y + tile, x:x + tile] = image
        cv2.rectangle(sheet, (x, y), (x + tile - 1, y + tile - 1), (60, 60, 60), 1)

        label = name.upper()
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)
        cv2.putText(sheet, label, (x + (tile - tw) // 2, y + tile + th + 8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2, cv2.LINE_AA)

    return sheet


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--landmarks", default="landmarks.npz")
    parser.add_argument("--sheet", default="docs/render-check.png")
    parser.add_argument("--out", default="docs/asl-alphabet-reference.png")
    parser.add_argument("--tile", type=int, default=TILE)
    parser.add_argument("--columns", type=int, default=COLUMNS)
    parser.add_argument("--from-sheet", action="store_true", help="Skip landmarks.npz even if present")
    args = parser.parse_args()

    if not args.from_sheet and os.path.exists(args.landmarks):
        print(f"Rendering fresh from {args.landmarks}...")
        class_names, images = from_landmarks(args.landmarks, args.tile)
    else:
        if not os.path.exists(args.sheet):
            raise SystemExit(
                f"Error: neither '{args.landmarks}' nor '{args.sheet}' exists. "
                "Run prepare_dataset.py, or check_render.py, first."
            )
        print(f"No landmarks.npz -- building from {args.sheet} instead (lower resolution).")
        class_names, images = from_existing_sheet(args.sheet, args.tile)

    sheet = compose(class_names, images, args.tile, args.columns)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    cv2.imwrite(args.out, sheet)
    print(f"Saved {args.out}  ({sheet.shape[1]}x{sheet.shape[0]}, {len(class_names)} letters)")


if __name__ == "__main__":
    main()
