"""Export the trained Keras model to ONNX, with the visualiser's taps as real outputs.

The repository shipped an .onnx file with nothing that could regenerate it, and the
translator dug the intermediate activations out at runtime by appending raw tensor
names like `sequential_1/conv2d_1/Relu:0` to the graph. Those names are generated by
the converter, so any retrain silently broke the visualiser.

Here the instrumented model is built in Keras first, with three declared outputs, and
the ONNX graph is then given stable names:

    logits          (N, 26)        raw scores, softmax applied by the caller
    conv1_relu      (N, H, W, 32)  first conv block, feeds the filter mosaic
    dense_features  (N, 128)       hidden layer, feeds the neuron grid

Usage:
    python export_onnx.py --model asl_cnn_model.keras --out asl_cnn_model.onnx
"""

import argparse
import os

import numpy as np

import preprocessing as pp

TAP_LAYERS = ("conv1_relu", "dense_features")
OUTPUT_NAMES = ("logits",) + TAP_LAYERS


def build_instrumented(tf, model):
    missing = [n for n in TAP_LAYERS if not any(l.name == n for l in model.layers)]
    if missing:
        raise SystemExit(
            f"Error: the model has no layers named {missing}. "
            "They are named in train_model.build_model(); retrain with the current version."
        )
    taps = [model.get_layer(name).output for name in TAP_LAYERS]
    return tf.keras.Model(model.inputs, [model.outputs[0]] + taps, name="asl_cnn_instrumented")


def rename_outputs(model_proto, mapping):
    """Attach Identity nodes so the graph exposes our names instead of the converter's."""
    from onnx import helper

    graph = model_proto.graph
    new_infos = []
    for info in graph.output:
        new_name = mapping[info.name]
        dims = []
        for dim in info.type.tensor_type.shape.dim:
            dims.append(dim.dim_value if dim.HasField("dim_value") else (dim.dim_param or None))
        new_infos.append(helper.make_tensor_value_info(new_name, info.type.tensor_type.elem_type, dims))
        graph.node.append(
            helper.make_node("Identity", [info.name], [new_name], name=f"rename_{new_name}")
        )

    del graph.output[:]
    graph.output.extend(new_infos)
    return model_proto


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model", default="asl_cnn_model.keras")
    parser.add_argument("--out", default="asl_cnn_model.onnx")
    parser.add_argument("--opset", type=int, default=15)
    parser.add_argument("--samples", type=int, default=200)
    args = parser.parse_args()

    if not os.path.exists(args.model):
        raise SystemExit(f"Error: '{args.model}' not found. Run train_model.py first.")

    import tensorflow as tf
    import tf2onnx
    import onnx
    import onnxruntime as ort

    # The exported model runs on ONNX Runtime's CPU kernels in production, so the Keras
    # reference used to verify parity must run on CPU too. Comparing against a GPU
    # forward pass instead compares two different kernel implementations rather than
    # checking the conversion: cuDNN and ONNX Runtime round differently, and at the
    # logit scale this model reaches that shows up as an absolute difference past the
    # tolerance even though nothing about the conversion is wrong.
    if tf.config.list_physical_devices("GPU"):
        tf.config.set_visible_devices([], "GPU")

    keras_model = tf.keras.models.load_model(args.model)
    size = int(keras_model.inputs[0].shape[1])
    instrumented = build_instrumented(tf, keras_model)
    print(f"Model loaded: input {size}x{size}, {keras_model.outputs[0].shape[-1]} classes")

    spec = (tf.TensorSpec((None, size, size, 3), tf.float32, name="input_image"),)

    @tf.function(input_signature=spec)
    def serve(x):
        return instrumented(x, training=False)

    print("Converting to ONNX...")
    model_proto, _ = tf2onnx.convert.from_function(serve, input_signature=spec, opset=args.opset)

    # Match converter outputs to Keras outputs by value rather than trusting the order:
    # a mislabelled tap would show the wrong picture in the visualiser without erroring.
    # The probe is rendered like a real skeleton rather than raw pixel noise: uniform
    # noise sits so far outside what BatchNorm was calibrated on that logits blow up to
    # extreme magnitudes, and at that scale ordinary GPU-vs-CPU float rounding produces
    # an absolute difference past the matching tolerance even though nothing is wrong.
    rng = np.random.default_rng(0)
    probe_points = rng.uniform(0.15, 0.85, size=(4, pp.NUM_LANDMARKS, 2)).astype(np.float32)
    probe = np.stack([pp.render_skeleton(p, size=size) for p in probe_points]).astype(np.float32)
    expected = [np.asarray(o) for o in instrumented.predict(probe, verbose=0)]

    session = ort.InferenceSession(model_proto.SerializeToString())
    actual = session.run(None, {session.get_inputs()[0].name: probe})
    actual_names = [o.name for o in session.get_outputs()]

    mapping = {}
    for target_name, want in zip(OUTPUT_NAMES, expected):
        best, best_err = None, np.inf
        for name, got in zip(actual_names, actual):
            if name in mapping or got.shape != want.shape:
                continue
            err = float(np.abs(got - want).max())
            if err < best_err:
                best, best_err = name, err
        if best is None or best_err > 1e-3:
            raise SystemExit(f"Error: could not match output '{target_name}' (best error {best_err}).")
        mapping[best] = target_name
        print(f"  {best}  ->  {target_name}  {want.shape}  (max|dif| {best_err:.2e})")

    onnx.save(rename_outputs(model_proto, mapping), args.out)
    print(f"\nSaved {args.out}  ({os.path.getsize(args.out) / 1e6:.1f} MB)")

    print(f"\nChecking Keras vs ONNX parity over {args.samples} rendered samples...")
    points = rng.uniform(0.15, 0.85, size=(args.samples, pp.NUM_LANDMARKS, 2)).astype(np.float32)
    batch = np.stack([pp.render_skeleton(p, size=size) for p in points]).astype(np.float32)

    keras_out = [np.asarray(o) for o in instrumented.predict(batch, verbose=0)]
    session = ort.InferenceSession(args.out)
    onnx_out = session.run(None, {session.get_inputs()[0].name: batch})
    names = [o.name for o in session.get_outputs()]

    worst = 0.0
    for name, got in zip(names, onnx_out):
        want = keras_out[OUTPUT_NAMES.index(name)]
        err = float(np.abs(got - want).max())
        worst = max(worst, err)
        print(f"  {name:16s} max|dif| = {err:.3e}")

    if worst > 1e-4:
        raise SystemExit(f"FAILED: largest difference {worst:.3e} exceeds 1e-4.")
    print(f"\nOK: parity confirmed (max {worst:.3e} < 1e-4). Outputs: {', '.join(names)}")


if __name__ == "__main__":
    main()
